// Run Demo Code
console.log("Bài Tập Javascript từ  9 - 16 ");
console.log("");
console.log("+)Dữ Liệu Mẫu");
createData(listProduct);
console.log(listProduct);
console.log("");
console.log("+)Tìm Tên sản phẩm theo Id = 9");
console.log("Cách 1: Sử dụng for");
console.log(fiterProductById(listProduct,9));
console.log("Cách 2: Sử dụng ES6");
console.log(fiterProductByIdUseFor(listProduct,9));
console.log("");
console.log("+)Trả về mảng sản phẩm quantity>0 và isDelete = false");
console.log("Cách 1: Sử dụng for");
console.log(fiterProductByQuantity(listProduct));
console.log("Cách 2: Sử dụng ES6");
console.log(fiterProductByQuantityUseFor(listProduct));
console.log("");
console.log("+)Trả về mảng sản phẩm dateSale>0 và isDelete = false");
console.log("Cách 1: Sử dụng for");
console.log(fiterProductBySaleDate(listProduct));
console.log("Cách 2: Sử dụng ES6");
console.log(fiterProductBySaleDateUseFor(listProduct));
console.log("");
console.log("+)Kiểm tra xem có sp nào có categoryId = 8 ko");
console.log("Cách 1: Sử dụng for");
console.log(isHaveProductInCategory(listProduct,8));
console.log("Cách 2: Sử dụng ES6");
console.log(isHaveProductInCategoryUseFor(listProduct,8));
console.log("");
console.log("+)Trả về mảng sản phẩm với các phần tử là [id,name] ,quantity>0 và isDelete = false");
console.log("Cách 1: Sử dụng for");
console.log(fiterProductBySaleDateVr2(listProduct));
console.log("Cách 2: Sử dụng ES6");
console.log(fiterProductBySaleDateVr2UseFor(listProduct));
console.log("");
console.log("Kết Thúc");
//End